---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create TEMP run dir
  file:
    path: "/var/run/{{ item.service_name }}"
    state: directory
    owner: "{{ systemd_user_name }}"
    group: "{{ systemd_group_name }}"
    mode: "02755"
  with_items: "{{ systemd_services }}"
  tags:
   - systemd-init

- name: Create TEMP lock dir
  file:
    path: "/var/lock/{{ item.service_name }}"
    state: directory
    owner: "{{ systemd_user_name }}"
    group: "{{ systemd_group_name }}"
    mode: "02755"
  with_items: "{{ systemd_services }}"
  tags:
    - systemd-init

- name: Create tmpfiles.d entry
  template:
    src: "systemd-tmpfiles.j2"
    dest: "/etc/tmpfiles.d/{{ systemd_tempd_prefix }}-{{ item.service_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  with_items: "{{ systemd_services }}"
  tags:
    - systemd-init

- name: Create tmpfiles.d entry
  template:
    src: "systemd-tmpfiles-lock.j2"
    dest: "/etc/tmpfiles.d/{{ systemd_tempd_prefix }}-{{ systemd_lock_path.strip('/') | replace('/', '-') }}-lock.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  tags:
    - systemd-init

- name: Place the systemd init script
  config_template:
    src: "systemd-service.j2"
    dest: "/etc/systemd/system/{{ item.service_name }}.service"
    mode: "0644"
    owner: "root"
    group: "root"
    config_overrides: "{{ item.init_config_overrides | default(systemd_service_config_overrides) }}"
    config_type: "ini"
  with_items: "{{ systemd_services }}"
  tags:
    - systemd-init

- name: Load service
  systemd:
    name: "{{ item.service_name }}"
    daemon_reload: yes
    enabled: "{{ item.enabled | default(systemd_service_enabled) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ systemd_services }}"
  tags:
    - systemd-init
