---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create TEMP run dir
  file:
    path: "/var/run/{{ item.value.service_name }}"
    state: directory
    owner: "{{ system_user_name }}"
    group: "{{ system_group_name }}"
    mode: "02755"
  with_dict: "{{ systemd_services }}"
  tags:
   - systemd-init

- name: Create TEMP lock dir
  file:
    path: "/var/lock/{{ item.value.service_name }}"
    state: directory
    owner: "{{ system_user_name }}"
    group: "{{ system_group_name }}"
    mode: "02755"
  with_dict: "{{ systemd_services }}"
  tags:
    - systemd-init

- name: Create tmpfiles.d entry
  template:
    src: "systemd-tmpfiles.j2"
    dest: "/etc/tmpfiles.d/{{ systemd_tempd_prefix }}-{{ item.value.service_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  with_dict: "{{ systemd_services }}"
  tags:
    - systemd-init

- name: Place the systemd init script
  config_template:
    src: "systemd-init.j2"
    dest: "/etc/systemd/system/{{ item.value.service_name }}.service"
    mode: "0644"
    owner: "root"
    group: "root"
    config_overrides: "{{ item.value.init_config_overrides | default({}) }}"
    config_type: "ini"
  with_dict: "{{ systemd_services }}"
  tags:
    - systemd-init

- name: Load service
  service:
   name: "{{ item.value.service_name }}"
   enabled: "yes"
   state: "started"
  with_dict: "{{ systemd_services }}"
  tags:
    - systemd-init
